/**
 * Chat Application by AubynJ
 * License under MIT & SAGA (Swedish Ason Group) AB
 * Uploaded on Thu Feb 21, 16:07:08
 */

module.exports = {
    USER_CONNECTED : 'connection',
    USER_DISCONNECTED : 'disconnect',
    USER_ALREADY_SIGN_IN : 'USER_CHATTING',
    USER_JOINED_NOW : 'USER_JUST_JOINED',
    JUST_JOINED_RESPONSE : 'USER_JOINED_RESPONSE',
    GET_NICKNAMES : 'GET_USERS',
    USER_NAME : "USER",
    SIGN_OUT : 'SIGN_OUT',
    MESSAGE_COMING : 'MESSAGE_SENDING',
    NEW_MESSAGE : 'NEW_MESSAGE',
    TYPING : 'TYPING',
    TYPING_NOW : 'TYPING_NOW',
    TYPING_STOP : 'STOP_TYPING',
    HISTORY : 'HISTORY',
    ROOM : 'GENERAL',
    PERSONAL_MSG : 'PERSONAL_SENDING',
    PERSONAL_REV : 'PERSONAL_RECEIVED',
    TYPING_PERSONAL : 'TYPING_PERSONAL',
    NOW_TYPING : 'NOW_TYPING',
    STOP_TYPING_PERSONAL : 'STOP_TYPING_PERSONAL',
    STOP_TYPING_PERSONAL_NOW : 'STOP_TYPING_PERSONAL_NOW',
    PERSONAL_HISTORY : 'PERSONAL_HISTORY'
}